force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expedition__c/Expedition__c.object-meta.xml
<CustomObject>
    <label>Expedition</label>
    <nameField>
        <label>Expedition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expeditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expedition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expedition_Action__c/Expedition_Action__c.object-meta.xml
<CustomObject>
    <label>Expedition Action</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Expedition Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expedition Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expedition_Action__c/fields/Expedition__c.field-meta.xml
<CustomField>
    <fullName>Expedition__c</fullName>
    <label>Expedition</label>
    <referenceTo>Expedition__c</referenceTo>
    <relationshipLabel>Expedition Actions</relationshipLabel>
    <relationshipName>Expedition_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expedition_Action__c/fields/Findings_Input__c.field-meta.xml
<CustomField>
    <fullName>Findings_Input__c</fullName>
    <label>Findings Input</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Expedition_Member__c/Expedition_Member__c.object-meta.xml
<CustomObject>
    <label>Expedition Member</label>
    <nameField>
        <displayFormat>EM-{0000}</displayFormat>
        <label>Expedition Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expedition Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expedition_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Expedition Members</relationshipLabel>
    <relationshipName>Expedition_Member</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expedition_Member__c/fields/Expedition__c.field-meta.xml
<CustomField>
    <fullName>Expedition__c</fullName>
    <label>Expedition</label>
    <referenceTo>Expedition__c</referenceTo>
    <relationshipLabel>Expedition Members</relationshipLabel>
    <relationshipName>Expedition_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expedition_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Expeditions_Member</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExpeditionInformationController.cls
public with sharing class ExpeditionInformationController {
   
    @AuraEnabled(cacheable=true)
    public static ExpeditionWrapper getUserActiveExpedition(Id uId){
        try {
            Expedition_Member__c activeExpedition = [SELECT Id, Name, Expedition__c, Expedition__r.Name, Expedition__r.Status__c FROM Expedition_Member__c WHERE Contact__r.User__c = :uId ];
            
            List<Expedition_Action__c> actions = [SELECT Id, Title__c, Description__c, Findings_Input__c FROM Expedition_Action__c WHERE Expedition__c = :activeExpedition.Expedition__c];

            ExpeditionWrapper expeditionWrapper = new ExpeditionWrapper();
            expeditionWrapper.expeditionName = activeExpedition.Expedition__r.Name;
            expeditionWrapper.expeditionStatus = activeExpedition.Expedition__r.Status__c;
            expeditionWrapper.expeditionId = activeExpedition.Expedition__c;
            expeditionWrapper.expeditionActions = actions;

            return expeditionWrapper;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
  public static String uploadFile(String base64, String filename, String recordId) {
        ContentVersion cv = createContentVersion(base64, filename);
        ContentDocumentLink cdl = createContentLink(cv.Id, recordId);
        if (cv == null || cdl == null) { return null; }
        return cdl.Id;
  }
  /*
   * @method createContentVersion() [private]
   * @desc Creates a content version from a given file's base64 and name
   * 
   * @param {String} base64 - base64 string that represents the file
   * @param {String} filename - full file name with extension, i.e. 'products.csv'
   * 
   * @return {ContentVersion} - returns the newly created ContentVersion, or null
   *   if there was an error inserting the record
   */
  private static ContentVersion createContentVersion(String base64, String filename) {
    ContentVersion cv = new ContentVersion();
    cv.VersionData = EncodingUtil.base64Decode(base64);
    cv.Title = filename;
    cv.PathOnClient = filename;
    try {
      insert cv;
      return cv;
    } catch(DMLException e) {
      System.debug(e);
      return null;
    }
  }

   /*
   * @method createContentLink() [private]
   * @desc Creates a content link for a given ContentVersion and record
   * 
   * @param {String} contentVersionId - Id of the ContentVersion of the file
   * @param {String} recordId - Id of the record you want to attach this file to
   * 
   * @return {ContentDocumentLink} - returns the newly created ContentDocumentLink, 
   *   or null if there was an error inserting the record
   */
  private static ContentDocumentLink createContentLink(String contentVersionId, String recordId) {
              if (contentVersionId == null || recordId == null) { return null; }
    ContentDocumentLink cdl = new ContentDocumentLink();
    cdl.ContentDocumentId = [
      SELECT ContentDocumentId 
      FROM ContentVersion 
      WHERE Id =: contentVersionId
    ].ContentDocumentId;
    cdl.LinkedEntityId = recordId;
    // ShareType is either 'V', 'C', or 'I'
    // V = Viewer, C = Collaborator, I = Inferred
    cdl.ShareType = 'V';
    try {
      insert cdl;
      return cdl;
    } catch(DMLException e) {
      System.debug(e);
      return null;
    }
  }

    class ExpeditionWrapper{
        @AuraEnabled public String expeditionName;
        @AuraEnabled public String expeditionId;
        @AuraEnabled public String expeditionStatus;
        @AuraEnabled public List<Expedition_Action__c> expeditionActions;

    }

    @AuraEnabled
    public static void completeExpedition(Id recordId){

        try{
            Expedition__c exp = new Expedition__c();
            exp.Id = recordId;
            exp.Status__c = 'Completed';
            update exp;
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
}